### ISSUE TITLE
не работает *&$%^ :<

### ISSUE THREAD

**Issue by Domaman202** [hohserg1/HoverHelm#1]

**Comment by hohserg1** [comment]
Привет) Че именно не работает? Напиши по шагам, как воспроизвести баг

**Comment by Domaman202** [comment]
ща видос сделаю

**Comment by Domaman202** [comment]
https://youtu.be/wI8xGdU0blw

**Comment by hohserg1** [comment]
В конфигурации нужно заменить строку address на первые несколько символов адреса сетевой карты.
![image](https://user-images.githubusercontent.com/35610168/113477371-05490000-948a-11eb-9b23-c1730a21d7f5.png)

**Comment by Domaman202** [comment]
ааааааа
блять пасиба
